CREATE TABLE AreaPesquisa(
	CODIGO INTEGER NOT NULL,
    INDICE_RELEVANCIA INTEGER NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

ALTER TABLE AreaPesquisa ADD CONSTRAINT AREA_pk PRIMARY KEY (CODIGO);

ALTER TABLE AREAPESQUISA RENAME TO AREA_PESQUISA;

DROP TABLE AREA_PESQUISA;

INSERT INTO AREA_PESQUISA(CODIGO, INDICE_RELEVANCIA, NOME, DESCRICAO)
VALUES (101, 2, 'IA', 'INTELIGENCIA ARTIFICIAL');

INSERT INTO AREA_PESQUISA(CODIGO, INDICE_RELEVANCIA, NOME, DESCRICAO)
VALUES (102, 3, 'GRAFOS', 'PARTICIONAMENTO DE GRAFOS');

CREATE TABLE PROJETO(
	CODIGO INTEGER NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DURACAO INTEGER NOT NULL,
    CODIGO_AREA INTEGER NOT NULL
);
--CHAVE PRIMARIA
ALTER TABLE PROJETO ADD CONSTRAINT PROJETO_PK PRIMARY KEY (CODIGO);

-- CGAVE ESTRANGEIRA QUE VEM DA AREA ED EPSQUISA
ALTER TABLE PROJETO ADD CONSTRAINT AREA_FK FOREIGN KEY (CODIGO_AREA) REFERENCES AREA_PESQUISA (CODIGO);

INSERT INTO PROJETO (CODIGO, TITULO, DURACAO, CODIGO_AREA)
VALUES (200, 'Particionamento com banco de dados', 70, 102);